<a href="https://colab.research.google.com/github/SuryawanshiKarishma/Task-2-Numpy/blob/main/Task_2_(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.version.version)

1.21.6


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([1,2,4,57,68,8,10])
print(x.size)

7


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info)

<function info at 0x7f4698c84950>


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(start = 10, stop = 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.array([1,2,4,57,68,8,10])
print(x[::-1])

[10  8 68 57  4  2  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x = np.arange(0,9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random((3,3))
print(x)

[[0.14570976 0.07342661 0.23441131]
 [0.65171511 0.49820222 0.13254809]
 [0.6591892  0.08644836 0.12401624]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random((10,10))
print(x)
print(np.max(x))
print(np.min(x))

[[0.72620038 0.90772162 0.12923144 0.27239407 0.82883706 0.56721615
  0.78510008 0.04429124 0.41245287 0.52758113]
 [0.60307531 0.34787977 0.13039418 0.13113905 0.63269479 0.3633899
  0.55568708 0.23185632 0.84236355 0.00738461]
 [0.74117484 0.28301311 0.94165544 0.01165069 0.41047755 0.54438593
  0.50273357 0.37548042 0.72792752 0.9055149 ]
 [0.2119568  0.05117942 0.21755102 0.49664683 0.42295462 0.70664053
  0.01969759 0.31359063 0.8373691  0.63169908]
 [0.57317778 0.28870915 0.78926194 0.03434689 0.68148728 0.91059592
  0.01544211 0.72865801 0.93672967 0.73108262]
 [0.66698131 0.29894533 0.17349767 0.49246593 0.78174326 0.02857367
  0.73736608 0.79795377 0.48084978 0.70047297]
 [0.22565861 0.56522033 0.43539753 0.70445291 0.63249111 0.2437296
  0.2261184  0.69984037 0.24856943 0.02933459]
 [0.26262797 0.06364371 0.94876134 0.82333604 0.36397799 0.84888435
  0.19494332 0.08302093 0.40167021 0.76597981]
 [0.2460297  0.09887515 0.00849778 0.81735202 0.24377884 0.54714488
  0.18395397 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x = np.random.random((30,30))
print(x)
print(np.mean(x))

[[0.46141478 0.17888949 0.46392958 0.1568202  0.43315412 0.67251198
  0.06454593 0.20746077 0.57922256 0.75609515 0.20694974 0.34409237
  0.90913177 0.73090752 0.25130027 0.28790764 0.12378729 0.60185388
  0.31936091 0.95022172 0.29177241 0.54185635 0.82732153 0.04964526
  0.32024318 0.58370125 0.82842344 0.32874179 0.65610351 0.36384683]
 [0.41209258 0.7650809  0.58395565 0.31627555 0.44259831 0.42726038
  0.38395798 0.27428811 0.56439383 0.9214324  0.75510919 0.64472746
  0.79071204 0.97370232 0.25881638 0.70263562 0.64995656 0.38286986
  0.43911924 0.27267769 0.23899148 0.69096782 0.38171596 0.28398064
  0.02086435 0.99881568 0.12837762 0.40916224 0.32492393 0.88358866]
 [0.10977025 0.8996028  0.48872135 0.20242314 0.13959181 0.4727491
  0.82358615 0.95424393 0.87361312 0.94001786 0.14312311 0.77880308
  0.43148963 0.05995092 0.68005564 0.07342129 0.73275899 0.71984756
  0.01609384 0.20262903 0.67177404 0.12340423 0.55232508 0.4987403
  0.09970259 0.18311915 0.53005801 0.54671808 0.

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((3,3))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.zeros((5,6))
x[1:-1,1:-1]=1
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x = np.diag([0,1,2,3,4])
print(x)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.eye(8)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[1. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
x = np.unravel_index(100, (6,7,8))
print(x)

(1, 5, 4)


In [ ]:
import numpy as np

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.81784722 0.91401669 0.58097521 0.02602398 0.81527744]
 [0.3973882  0.63576526 0.03256672 0.52482611 0.19848082]
 [0.68342176 0.65542481 0.13287597 0.44612763 0.35303571]
 [0.38033072 0.95587364 0.01828253 0.4914163  0.95557536]
 [0.13032087 0.48853816 0.93612825 0.98759105 0.99551877]]
[[0.81818977 0.91659941 0.57580006 0.00792178 0.81556012]
 [0.38793656 0.63186639 0.01461693 0.51834302 0.18439583]
 [0.680633   0.65198388 0.11726279 0.43781133 0.34255093]
 [0.37048175 0.95943138 0.         0.48415496 0.95912615]
 [0.11464817 0.48120978 0.93922604 0.99188761 1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a = np.random.random((5,3))
b = np.random.random((3,2))
#res = np.dot(a,b)
#print(res)
print(a @ b)

[[0.83126348 0.9437186 ]
 [1.17735876 1.25153729]
 [1.03964583 1.18413093]
 [1.05219254 1.1794555 ]
 [0.69504802 0.72773063]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(15)
x[(x>=3) & (x<=8)]*=(-1)
print(x)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
10
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.random((5,5))
print(x)
print(np.round(x,2))


[[0.21007829 0.97328436 0.3080697  0.4497555  0.38821968]
 [0.87552129 0.04456875 0.99110233 0.90467427 0.61057342]
 [0.9339612  0.98072153 0.09143745 0.55050392 0.67718457]
 [0.25399123 0.12290732 0.00910106 0.25420169 0.11497595]
 [0.813574   0.97367123 0.88672923 0.23759334 0.03561925]]
[[0.21 0.97 0.31 0.45 0.39]
 [0.88 0.04 0.99 0.9  0.61]
 [0.93 0.98 0.09 0.55 0.68]
 [0.25 0.12 0.01 0.25 0.11]
 [0.81 0.97 0.89 0.24 0.04]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.array([3,6,9,12,15,18])
y = np.array([2,4,6,8,10,12])
print(np.intersect1d(x,y))

[ 6 12]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
not true

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today = np.datetime64('today', 'D')
yest = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomm = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Today:", today)
print("Yesterday:", yest)
print("Tomorrow:", tomm)

Today: 2022-09-18
Yesterday: 2022-09-17
Tomorrow: 2022-09-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x = np.random.uniform(0,10,10)

print (x - x%1)
print (np.floor(x))
print (np.ceil(x)-1)
print (x.astype(int))

[3. 2. 5. 3. 1. 2. 9. 5. 8. 1.]
[3. 2. 5. 3. 1. 2. 9. 5. 8. 1.]
[3. 2. 5. 3. 1. 2. 9. 5. 8. 1.]
[3 2 5 3 1 2 9 5 8 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5))
x = x + np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for i in range(10):
        yield i
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
print(np.linspace(0,1,11,endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(10)
x.sort()
print(x)

[0.2118811  0.26617836 0.30550238 0.44499574 0.62302684 0.64090985
 0.89233374 0.91707194 0.92325592 0.92842194]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,4,7)
B = np.random.randint(0,4,7)
res = np.allclose(A,B)
print(res)


False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a= np.random.random((10,2))
x,y = a[:,0], a[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.01544875 0.69230856 0.13655814 0.01951935 0.07092222 0.49584731
 0.62937953 0.1193683  0.36656371 0.05747191]
[0.01544875 0.         0.13655814 0.01951935 0.07092222 0.49584731
 0.62937953 0.1193683  0.36656371 0.05747191]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
Z = np.zeros((3,3), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,3),
                             np.linspace(0,1,3))
print(Z)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.arange(10)
y = x + 0.5
z = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(z))

33961.93294480236


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
x = np. arange(1001)
np.set_printoptions(threshold=np.inf)
print(x)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.random.random(10)
print(x)
print(x.argmin())


[0.06115045 0.31529932 0.81217242 0.6514061  0.28118211 0.12815264
 0.07106037 0.3033914  0.90816168 0.4935503 ]
0


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
x = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
a = np.random.random((100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.23580391 0.25010638 1.07416605 0.71248394 0.69287167
  0.80684186 0.77424027 0.28332772 0.57015878 0.92708803 0.93142693
  0.54590057 0.88667743 0.43711012 0.93173198 0.70314089 1.08848091
  0.29592229 0.19485022 0.48508068 1.00623204 0.28138457 0.25677125
  0.21444358 0.14340237 0.67362027 0.82615469 0.21369616 0.24850899
  0.56885042 0.75598971 0.98182457 0.49163513 0.66033657 0.83304746
  0.22341683 0.51851927 0.6714229  1.08012008 0.52068852 0.39259391
  0.57552084 0.673236   0.25543098 0.60116503 0.36732833 0.70854656
  0.41369726 0.56736721 0.77399568 0.21825654 0.00915788 0.37107907
  0.85592288 0.70740829 0.27105525 0.76798257 0.40350957 0.78235225
  0.71320242 1.06526889 0.63493079 0.38696254 0.42590635 0.75320596
  0.72080342 0.7205253  1.04289812 0.75578918 0.76583587 0.83849567
  0.5308913  0.50456596 0.61098766 0.54454304 0.90159876 0.63318467
  0.96773867 0.31256477 0.21074407 0.22422692 0.60564239 0.24416803
  0.191092   1.03412034 0.93626736 0.34680386 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x = np.arange(10, dtype=np.float32)
x_1 = x.astype(np.float32, copy=False)
x_1[0] = 2
print(x)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
            ''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
x = np.zeros((8,2))
np.put(x,5,1)
print(x)

[[0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(5, 10)
print(x)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[0.02938864 0.10942918 0.13423529 0.37692051 0.01906419 0.23230971
  0.36991582 0.32766906 0.53451563 0.0872236 ]
 [0.53481555 0.64930218 0.95215951 0.90230311 0.71171297 0.36470915
  0.13063986 0.50235837 0.15294581 0.82130084]
 [0.03612796 0.86766921 0.25253686 0.54092072 0.11255221 0.9035203
  0.58924808 0.64434722 0.60366091 0.1851899 ]
 [0.06685653 0.07363886 0.12833073 0.61423459 0.93521867 0.58241669
  0.28367052 0.00210078 0.7063621  0.71630633]
 [0.53981633 0.04640199 0.55025466 0.45491411 0.4291196  0.76753103
  0.03653368 0.2166816  0.85575725 0.27333395]]
[[-0.19267853 -0.11263798 -0.08783187  0.15485335 -0.20300298  0.01024255
   0.14784866  0.1056019   0.31244847 -0.13484356]
 [-0.03740919  0.07707745  0.37993478  0.33007837  0.13948823 -0.20751558
  -0.44158487 -0.06986637 -0.41927892  0.2490761 ]
 [-0.43744938  0.39409188 -0.22104048  0.06734339 -0.36102513  0.42994297
   0.11567074  0.17076988  0.13008357 -0.28838744]
 [-0.34405705 -0.33727472 -0.28258285  0.20332101 

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,15,(5,5))
print(x)
print(x[x[:,1].argsort()])

[[11  2  0 12  7]
 [ 9  4  1  7  6]
 [ 3  9  7  1  5]
 [14  5 13  0  7]
 [ 2  3  7  8  0]]
[[11  2  0 12  7]
 [ 2  3  7  8  0]
 [ 9  4  1  7  6]
 [14  5 13  0  7]
 [ 3  9  7  1  5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x = np.random.randint(0,5,(5,10))
print(x)
print((~x.any(axis=0)).any())

[[2 0 2 2 4 4 3 1 4 2]
 [3 3 4 4 4 1 1 3 2 4]
 [3 3 2 0 0 1 3 1 2 4]
 [4 2 1 2 4 2 0 2 0 0]
 [1 3 2 4 3 3 3 1 3 4]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
arr = np.array([8, 7, 1, 5, 3, 4])
x = 2
difference_array = np.absolute(arr-x)
index = difference_array.argmin()
print("Element:", arr[index])
print("Index:", index)

Element: 1
Index: 2


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a = np.arange(5).reshape(1, 3)
b = np.arange(5).reshape(3, 1)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
x += np.bincount(y, minlength=len(x))
#z = np.add.at(x, y, 1)
print(x)

[2. 3. 3. 3. 3. 5. 5. 1. 2. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
x = [3,4,1,2,3,6]
y = [1,5,6,3,9,4]
z = np.bincount(y,x)
print(z)

[0. 3. 0. 2. 6. 4. 1. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(6,4,2,8))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[ 63  82  68  90]
 [ 56  96  78 104]
 [ 83  83  61  75]
 [ 77  71  73  72]
 [ 74  67  63  75]
 [ 94  79  94  61]]
[[ 63  82  68  90]
 [ 56  96  78 104]
 [ 83  83  61  75]
 [ 77  71  73  72]
 [ 74  67  63  75]
 [ 94  79  94  61]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
x = np.random.uniform(0,1,100)
y = np.random.randint(0,10,100)
x_sums = np.bincount(y, weights=x)
x_counts = np.bincount(y)
x_means = x_sums / x_counts
print(x_means)

[0.61430444 0.57810497 0.48424822 0.48051313 0.46293506 0.4403529
 0.6289462  0.58413712 0.37888455 0.45242948]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
x = np.random.uniform(0,1,(10,10))
y = np.random.uniform(0,1,(10,10))
z = np.diag(np.dot(x, y))
print(z)

[3.1985562  1.93556961 2.75521947 2.75120778 2.8385267  2.77920612
 2.6446989  2.70350677 2.03549095 1.94956749]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
x = np.array([1,2,3,4,5])
n = 3
y = np.zeros(len(x) + (len(x)-1)*(n))
y[::n+1] = x
print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x * y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [ ]:
import numpy as np

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
x = np.arange(9).reshape(3,3)
print(x)
x[[0,1]] = x[[1,0]]
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  5) ( 0, 16) ( 3, 52) ( 3, 94) ( 5, 16) ( 6, 23) ( 6, 29) ( 7, 62)
 ( 7, 67) (16, 17) (16, 61) (17, 61) (19, 61) (19, 93) (23, 29) (24, 34)
 (24, 38) (34, 38) (35, 36) (35, 91) (36, 91) (46, 47) (46, 64) (47, 62)
 (47, 64) (47, 71) (52, 94) (61, 93) (62, 67) (62, 71)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
c = np.bincount([1,1,2,3,4,4,6])
x = np.repeat(np.arange(len(c)), c)
print(x)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
arr = [1, 7, 5, 3, 8]
i = 1
moving_averages = []
cum_sum = np.cumsum(arr);
while i <= len(arr):

    window_average = round(cum_sum[i-1] / i, 2)
    moving_averages.append(window_average)
    i += 1 
print(moving_averages)

[1.0, 4.0, 4.33, 4.0, 4.8]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
x = rolling(np.arange(10), 3)
print(x)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
x = np.random.randint(0,2,100)
np.logical_not(x, out=x)

x = np.random.uniform(-1.0,1.0,100)
np.negative(x, out=x)

array([ 0.78494263,  0.39240861,  0.0741072 ,  0.59241805, -0.57069188,
       -0.15029193, -0.76882113, -0.39029709,  0.14903878,  0.9483896 ,
       -0.03971723,  0.50941713, -0.5491401 ,  0.11335748,  0.19705768,
        0.12610166, -0.8130988 , -0.95077923,  0.36791185,  0.47833875,
       -0.12570322, -0.31584962,  0.42142041,  0.42867505,  0.2255437 ,
       -0.35231826,  0.23844945, -0.2847279 , -0.82408002,  0.30175766,
       -0.47781519,  0.8859626 , -0.37939385,  0.72299748, -0.09137693,
       -0.13472567, -0.73127155, -0.56249277, -0.63451945,  0.96616968,
       -0.31041732, -0.84867723, -0.36092952,  0.00380305, -0.88396418,
       -0.97652145,  0.69698211, -0.62860781, -0.14425524,  0.841673  ,
       -0.61352872, -0.74186883,  0.63497878,  0.33805541, -0.96372351,
        0.40588638, -0.59149266, -0.7849216 ,  0.06060535, -0.11476763,
       -0.42052721, -0.71464646,  0.59572291,  0.55698598,  0.95445453,
        0.97846751, -0.28247238,  0.81700372,  0.92903245, -0.38

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
x = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(x) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,8,16)
print(np.bincount(Z).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
x = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
y = stride_tricks.as_strided(x, shape=(i, j, n, n), strides=x.strides + x.strides)
print(y)

[[[[0 0 1]
   [4 2 2]
   [1 0 2]]

  [[0 1 1]
   [2 2 2]
   [0 2 3]]

  [[1 1 3]
   [2 2 0]
   [2 3 2]]

  [[1 3 1]
   [2 0 2]
   [3 2 3]]

  [[3 1 3]
   [0 2 1]
   [2 3 3]]

  [[1 3 1]
   [2 1 2]
   [3 3 3]]

  [[3 1 2]
   [1 2 3]
   [3 3 4]]

  [[1 2 4]
   [2 3 1]
   [3 4 4]]]


 [[[4 2 2]
   [1 0 2]
   [2 0 3]]

  [[2 2 2]
   [0 2 3]
   [0 3 0]]

  [[2 2 0]
   [2 3 2]
   [3 0 1]]

  [[2 0 2]
   [3 2 3]
   [0 1 0]]

  [[0 2 1]
   [2 3 3]
   [1 0 4]]

  [[2 1 2]
   [3 3 3]
   [0 4 4]]

  [[1 2 3]
   [3 3 4]
   [4 4 0]]

  [[2 3 1]
   [3 4 4]
   [4 0 0]]]


 [[[1 0 2]
   [2 0 3]
   [4 1 0]]

  [[0 2 3]
   [0 3 0]
   [1 0 0]]

  [[2 3 2]
   [3 0 1]
   [0 0 1]]

  [[3 2 3]
   [0 1 0]
   [0 1 3]]

  [[2 3 3]
   [1 0 4]
   [1 3 2]]

  [[3 3 3]
   [0 4 4]
   [3 2 4]]

  [[3 3 4]
   [4 4 0]
   [2 4 0]]

  [[3 4 4]
   [4 0 0]
   [4 0 0]]]


 [[[2 0 3]
   [4 1 0]
   [3 1 1]]

  [[0 3 0]
   [1 0 0]
   [1 1 4]]

  [[3 0 1]
   [0 0 1]
   [1 4 2]]

  [[0 1 0]
   [0 1 3]
   [4 2 3]]

  [[1 0 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
x = np.ones((16,16))
k = 4
print(x)
result = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                      np.arange(0, x.shape[1], k), axis=1)
print(result)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
arr = np.array([2, 0,  1, 5, 4, 1, 9])  
print(arr)
sorted_index_array = np.argsort(arr)
sorted_array = arr[sorted_index_array]
print(sorted_array)
n = 1
rslt = sorted_array[-n : ]
print("{} largest value:".format(n), rslt[0])

[2 0 1 5 4 1 9]
[0 1 1 2 4 5 9]
1 largest value: 9


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
x = np.array([("Karishma", 8, 23),
              ("Suryawanshi", 11, 100 )])
y = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S15, i8, i8')
print(y)

[(b'Karishma',  8,  23) (b'Suryawanshi', 11, 100)]


In [ ]:
import numpy as np

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e5))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

21.8 ms ± 466 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
372 µs ± 32.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
442 µs ± 11.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,6,(8,3))
B = np.random.randint(0,6,(2,2))
print(A)
print(B)
temp = (A[..., np.newaxis, np.newaxis] == B)
rows = (temp.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[3 0 4]
 [2 1 5]
 [3 0 2]
 [2 2 1]
 [5 0 2]
 [0 3 5]
 [5 0 0]
 [1 5 5]]
[[3 1]
 [4 2]]
[0 1 2 3]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
A = np.random.randint(0,4,(6,3))
print(A)
B = np.logical_and.reduce(A[:,1:] == A[:,:-1], axis=1)
res = A[~B]
print(res)

[[0 0 2]
 [1 1 3]
 [1 0 3]
 [3 1 2]
 [0 2 2]
 [3 1 3]]
[[0 0 2]
 [1 1 3]
 [1 0 3]
 [3 1 2]
 [0 2 2]
 [3 1 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
A = np.array([10, 4, 18, 9, 30, 6])
print(A)
B = ((A.reshape(-1,1) & (2**np.arange(5))) != 0).astype(int)
print(B[:,::-1])

[10  4 18  9 30  6]
[[0 1 0 1 0]
 [0 0 1 0 0]
 [1 0 0 1 0]
 [0 1 0 0 1]
 [1 1 1 1 0]
 [0 0 1 1 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
x = np.random.randint(0,2,(3,3))
print(x)
y = np.unique(x, axis = 0)
print('Unique Rows:',y, sep = '\n')

[[0 0 0]
 [1 1 1]
 [0 0 1]]
Unique Rows:
[[0 0 0]
 [0 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)
print(A)
print(B)
sum = np.einsum('i->', A)       
mul = np.einsum('i,i->i', A, B) 
inner = np.einsum('i,i', A, B)    
outer = np.einsum('i,j->ij', A, B)
print("Sum:", sum)
print("Mul:", mul)
print("Sum:", inner)
print("Sum:", outer)

[0.17025126 0.73965452 0.76284936 0.89778419 0.34589169]
[0.62079945 0.97025551 0.25026365 0.75016322 0.40654654]
Sum: 2.9164310171550962
Mul: [0.10569189 0.71765387 0.19091347 0.67348468 0.14062107]
Sum: 1.828364977832165
Sum: [[0.10569189 0.16518722 0.0426077  0.12771623 0.06921506]
 [0.45917712 0.71765387 0.18510864 0.55486161 0.30070398]
 [0.47357647 0.7401588  0.19091347 0.57226154 0.31013377]
 [0.55734393 0.87108006 0.22468275 0.67348468 0.36499106]
 [0.21472937 0.33560332 0.08656412 0.25947522 0.14062107]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 1*np.pi, 0.1)
a = 1
v1 = a*phi*np.cos(phi)
v2 = a*phi*np.sin(phi)
dr = (np.diff(v1)**2 + np.diff(v2)**2)**.5
r = np.zeros_like(v1)

r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)

v1_int = np.interp(r_int, r, v1)
v2_int = np.interp(r_int, r, v2)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.27379066  0.12322435]
